# Generated by Django 3.2.7 on 2022-12-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
