# Generated by Django 3.2.7 on 2022-12-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanbook', '0003_auto_20221121_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbook',
            name='book_type',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
