# Generated by Django 3.2.7 on 2022-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
