# Generated by Django 3.2.7 on 2022-12-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
    ]
